yolo_model:

  config_file:
    name: yolov2-tiny-voc.cfg
  weight_file:
    name: yolov2-tiny-voc.weights
  threshold:
    value: 0.65
  detection_classes:
    names:
      # - aeroplane
      # - bicycle
      # - bird
      # - boat
      # - bottle
      # - bus
      # - car
      # - cat
      # - chair
      # - cow
      # - diningtable
      # - dog
      # - horse
      # - motorbike
      - person
      # - pottedplant
      # - sheep
      # - sofa
      # - train
      # - tvmonitor
