// Generated by gencpp from file darknet_ros_msgs/ComputeBox.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_COMPUTEBOX_H
#define DARKNET_ROS_MSGS_MESSAGE_COMPUTEBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct ComputeBox_
{
  typedef ComputeBox_<ContainerAllocator> Type;

  ComputeBox_()
    : id(0)
    , Class()
    , probability(0.0)
    , xmin(0.0)
    , ymin(0.0)
    , xmax(0.0)
    , ymax(0.0)  {
    }
  ComputeBox_(const ContainerAllocator& _alloc)
    : id(0)
    , Class(_alloc)
    , probability(0.0)
    , xmin(0.0)
    , ymin(0.0)
    , xmax(0.0)
    , ymax(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef double _probability_type;
  _probability_type probability;

   typedef double _xmin_type;
  _xmin_type xmin;

   typedef double _ymin_type;
  _ymin_type ymin;

   typedef double _xmax_type;
  _xmax_type xmax;

   typedef double _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeBox_

typedef ::darknet_ros_msgs::ComputeBox_<std::allocator<void> > ComputeBox;

typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBox > ComputeBoxPtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBox const> ComputeBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.Class == rhs.Class &&
    lhs.probability == rhs.probability &&
    lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7173ddff0b758de1103e5df884a8f8b9";
  }

  static const char* value(const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7173ddff0b758de1ULL;
  static const uint64_t static_value2 = 0x103e5df884a8f8b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/ComputeBox";
  }

  static const char* value(const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"string Class\n"
"float64 probability\n"
"float64 xmin\n"
"float64 ymin\n"
"float64 xmax\n"
"float64 ymax\n"
;
  }

  static const char* value(const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.Class);
      stream.next(m.probability);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::ComputeBox_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "xmin: ";
    Printer<double>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<double>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<double>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<double>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_COMPUTEBOX_H
