// Generated by gencpp from file darknet_ros_msgs/ComputeBoxes.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MSGS_MESSAGE_COMPUTEBOXES_H
#define DARKNET_ROS_MSGS_MESSAGE_COMPUTEBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <darknet_ros_msgs/ComputeBox.h>

namespace darknet_ros_msgs
{
template <class ContainerAllocator>
struct ComputeBoxes_
{
  typedef ComputeBoxes_<ContainerAllocator> Type;

  ComputeBoxes_()
    : compute_box()  {
    }
  ComputeBoxes_(const ContainerAllocator& _alloc)
    : compute_box(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >::other >  _compute_box_type;
  _compute_box_type compute_box;





  typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeBoxes_

typedef ::darknet_ros_msgs::ComputeBoxes_<std::allocator<void> > ComputeBoxes;

typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBoxes > ComputeBoxesPtr;
typedef boost::shared_ptr< ::darknet_ros_msgs::ComputeBoxes const> ComputeBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator2> & rhs)
{
  return lhs.compute_box == rhs.compute_box;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator1> & lhs, const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace darknet_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a0189e0ccd8b7029250c17e4ab7ef8f";
  }

  static const char* value(const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a0189e0ccd8b702ULL;
  static const uint64_t static_value2 = 0x9250c17e4ab7ef8fULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros_msgs/ComputeBoxes";
  }

  static const char* value(const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ComputeBox[] compute_box\n"
"================================================================================\n"
"MSG: darknet_ros_msgs/ComputeBox\n"
"int16 id\n"
"string Class\n"
"float64 probability\n"
"float64 xmin\n"
"float64 ymin\n"
"float64 xmax\n"
"float64 ymax\n"
;
  }

  static const char* value(const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.compute_box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros_msgs::ComputeBoxes_<ContainerAllocator>& v)
  {
    s << indent << "compute_box[]" << std::endl;
    for (size_t i = 0; i < v.compute_box.size(); ++i)
    {
      s << indent << "  compute_box[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::darknet_ros_msgs::ComputeBox_<ContainerAllocator> >::stream(s, indent + "    ", v.compute_box[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MSGS_MESSAGE_COMPUTEBOXES_H
